services:
  postgres:
    image: postgres:16
    container_name: car-rental-postgres
    environment:
      POSTGRES_USER: car_rental_user
      POSTGRES_PASSWORD: car_rental_pass
      POSTGRES_DB: car_rental_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: